openapi: 3.0.1
info:
  title: Gesti칩n de Tareas API
  description: API para la gesti칩n de tareas de NUEVO SPA
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: User
    description: Operaciones de usuarios
  - name: Task
    description: Operaciones de tareas
paths:
  /auth/login:
    post:
      tags:
        - User
      summary: Iniciar sesi칩n
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: JWT token
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Credenciales inv치lidas
  /tasks:
    get:
      tags:
        - Task
      summary: Listar tareas
      responses:
        '200':
          description: Lista de tareas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
        - Task
      summary: Crear tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        '201':
          description: Tarea creada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    put:
      tags:
        - Task
      summary: Actualizar tarea
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskRequest'
      responses:
        '200':
          description: Tarea actualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
    delete:
      tags:
        - Task
      summary: Eliminar tarea
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Tarea eliminada
components:
  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
      required:
        - title
        - description
        - status
    TaskRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
      required:
        - title
        - description
        - status
